before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RT2TWA2gu0xN7r0uWN/eK4VT6AX32hgqUGWmwW8sf3Mpt5Eygph36MSPmDJNMZzja9Rh4oAwvdfRIDCtwVXYIahmFXhh+/q8XImPiK25ry2/KIfQuOMmG5Z8BzyN6duRBLCHpdfs6Zl2CFZ+RzeF+03WuGu2I2+JacD4OgEbZS+kh9yi94r41H9UfIrILcYvMPBRJLW3+7kVJjtMGdcWUz8/yYiafEyYlJi7oRzJ+Nb+QCThUbsGwht+K4WNHA7JErLAlAaT3+yfieTZL66RuIDhWTPWJagN2/yWiAqRWJLUi7woxVcWwhkZXC5cdTajYDgTfw4quZ5QOu0IYNgKhYWs+h1xt8EiqV2CRRVvXbYwHpyNkEBVFyIsfRaXGaxetjGym2ufxjDY6RaZHG7N2N5WEKonNCOSBkZsT+cUe+gLAzRZstEv0rsX9driHKLPQc2M82rZTufHVWYTRnvGIGuWnW8FbWE8F/d0YPIiU4RdCFvT1Wta/6ETlLjChrO/pZLMDPWLz31P/7mODyn1CfF5WT8j8Fh/G6v8Yiw2FORCvUGaHUE2d/eyYoVGRwBu42wRbUdjYU2dS568Zq3rmte/xN712t5OX/CuEgSQYrkNkJd72dmla4UVV3jBW2CQFJ1DaBnHd3Hb6nj1QqpnUWC51RRcHgr7gFUfcbDcGok= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
